name: ci

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ensure this project runs
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          another_input: "whatever"
